---

name: Grok with AWK
author: norwd
description: "GitHub Action to grok stuff... with AWK!"

branding:
  icon: code
  color: red

inputs:
  input:
    required: false
    description: |
      The input to the awk program.

  input-file:
    required: false
    description: |
      The pathname of the file containing the input to the awk program.

  separator:
    required: false
    description: |
      The input field separator.

  program:
    required: false
    description: |
      The text of the awk program.

  program-file:
    required: false
    description: |
      The pathname of the file containing an awk program.

outputs:
  result:
    value: ${{ steps.awk.outputs.result }}
    description: |
      The result of the awk script.

runs:
  using: "composite"
  steps:
    - name: "Get Config"
      id: config
      shell: bash
      run: |
        echo "data-file=${{ runner.temp }}/std.in" >> "${GITHUB_OUTPUT}"
        echo "prog-file=${{ runner.temp }}/gr.awk" >> "${GITHUB_OUTPUT}"

    - name: "Create Standard Input"
      shell: bash
      run: touch "${{ steps.config.outputs.data-file }}"

    - name: "Add Input File to Standard Input"
      if: inputs.input-file != ''
      shell: bash
      run: cat "${DATA_FILE}" | tee -a "${{ steps.config.outputs.data-file }}"
      env:
        DATA_FILE: ${{ inputs.input-file }}

    - name: "Add Raw Input to Standard Input"
      if: inputs.input != ''
      shell: bash
      run: echo "${DATA_TEXT}" | tee -a "${{ steps.config.outputs.data-file }}"
      env:
        DATA_TEXT: ${{ inputs.input }}

    - name: "Debug Grawk Input"
      if: runner.debug == 1
      shell: bash
      run: cat "${{ steps.config.outputs.data-file }}"

    - name: "Create Program"
      shell: bash
      run: touch "${{ steps.config.outputs.prog-file }}"

    - name: "Add Program File to Program"
      if: inputs.program-file != ''
      shell: bash
      run: cat "${PROG_FILE}" | tee -a "${{ steps.config.outputs.prog-file }}"
      env:
        PROG_FILE: ${{ inputs.program-file }}

    - name: "Add Raw Program to Program"
      if: inputs.program != ''
      shell: bash
      run: echo "${PROG_TEXT}" | tee -a "${{ steps.config.outputs.prog-file }}"
      env:
        PROG_TEXT: ${{ inputs.program }}

    - name: "Debug Grawk Program"
      if: runner.debug == 1
      shell: bash
      run: cat "${{ steps.config.outputs.prog-file }}"

    - name: "Run awk script"
      id: awk
      shell: bash
      env:
        SEPARATOR: ${{ inputs.separator }}
      run: |
        delimiter="$(openssl rand -hex 8)"
        echo "result<<${delimiter}" >> "${GITHUB_OUTPUT}"
        cat "${{ steps.config.outputs.data-file }}" | awk ${{ inputs.separator && '-F "${SEPARATOR}"' || '' }} -f "${{ steps.config.outputs.prog-file }}" | tee -a "${GITHUB_OUTPUT}"
        echo "${delimiter}" >> "${GITHUB_OUTPUT}"
